spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
<<<<<<< HEAD
<<<<<<< HEAD
=======
    name: ebook-shop
>>>>>>> 794cfb7 (Prepare for deployment)
=======
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
>>>>>>> af01bf5 (Add hibernate dialect)

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes
